/**
 * QUIZ_BANK — 難易度別問題バンク
 *
 * 構造:
 *   window.QUIZ_BANK.easy   → 初級問題の配列
 *   window.QUIZ_BANK.medium → 中級問題の配列
 *   window.QUIZ_BANK.hard   → 上級問題の配列
 *
 * 各要素: { question: "問題文", answer: "答え" }
 *
 * 問題を追加するときはそれぞれの配列の末尾に
 *   { question: "...", answer: "..." },
 * を追記するだけでOKです。
 */

window.QUIZ_BANK = {

  /* ============================================================
     初級 (easy) - 瞬発力重視
     ============================================================ */
  easy: [
    { question: "千鳥のメンバーは、大悟と誰？", answer: "ノブ" },
    { question: "ナイアガラの滝があるのは、北米・南米どっち？", answer: "北米" },
    { question: "「夢心地（ゆめごこち）」なのは、起きている・寝ているどっち？", answer: "起きている" },
    { question: "モンゴル帝国を建国したのは誰？", answer: "チンギス・ハン" },
    { question: "国土が広いのは、カナダ・アメリカどっち？", answer: "カナダ" },
    { question: "31日がない月。9月の次は、何月？", answer: "11月" },
    { question: "スポーツの「最優秀選手」を英字3文字で？", answer: "MVP" },
    { question: "高級メロン「夕張メロン」の名産地はどこ？", answer: "北海道" },
    { question: "アメリカの西海岸に面している海はどこ？", answer: "太平洋" },
    { question: "ゲーム『あつ森』の「森」は、何の森？", answer: "どうぶつの森" },
    { question: "大きい数値は、3分の1・25%どっち？", answer: "3分の1" },
    { question: "「サシで飲もう」と言われた時、合計人数は何人？", answer: "2人" },
    { question: "植物の光合成によって、新しく作られる気体は？", answer: "酸素" },
    { question: "270秒は、何分何秒のこと？", answer: "4分30秒" },
    { question: "「土砂降り」で、空から降ってくるものは何？", answer: "雨" },
    { question: "サッカーは蹴球、では「バスケットボール」は？", answer: "籠球" },
    { question: "親の「コネ」で入社。この「コネ」の正式名称は？", answer: "コネクション" },
    { question: "温泉地。有名な「草津温泉」があるのは何県？", answer: "群馬県" },
    { question: "「一獲千金」の漢数字をすべて足すと？", answer: "1001" },
    { question: "食べられるのは、春雨・秋雨どっち？", answer: "春雨" },
    { question: "将棋で、一番最初に駒を動かすのは先手・後手どっち？", answer: "先手" },
    { question: "普通のサイコロの目で、最大の奇数は何？", answer: "5" },
    { question: "かけ算の九九で、最も答えが大きくなるのは？", answer: "81" },
    { question: "長野県の名物おやつは、おかき・おやきどっち？", answer: "おやき" },
    { question: "今何問目？", answer: "(画面を確認して)" },
    { question: "今何問目？", answer: "(画面を確認して)" },
    { question: "今何問目？", answer: "(画面を確認して)" },
    { question: "今何問目？", answer: "(画面を確認して)" },
    { question: "今何問目？", answer: "(画面を確認して)" },
    { question: "あと何問で終わり？", answer: "(画面を確認して)" },
    { question: "あと何問で終わり？", answer: "(画面を確認して)" },
    { question: "あと何問で終わり？", answer: "(画面を確認して)" },
    { question: "あと何問で終わり？", answer: "(画面を確認して)" },
    { question: "あと何問で終わり？", answer: "(画面を確認して)" },
    { question: "KLCCの『CC』は何の略？", answer: "City Centre" },
    { question: "ドリアンは果物の王様？王女？", answer: "王様" },
    { question: "マレーシアの車で最も多い国産メーカーは？", answer: "プロトン" },
    { question: "雨季によくある夕方の大雨を何という？", answer: "スコール" },
    { question: "イスラム教徒が断食する月は？", answer: "ラマダン" },
    { question: "マレーシアの最高峰は？", answer: "キナバル山" },
    { question: "キナバル山がある州は？", answer: "サバ州" },
    { question: "第一次大戦は何世紀？", answer: "20世紀" },
    { question: "楔形文字の文明は？", answer: "メソポタミア文明" },
    { question: "第一次大戦の引き金となった事件は？", answer: "サラエボ事件" },
    { question: "『種の起源』を書いた人物は？", answer: "ダーウィン" },
    { question: "G7に入るアジアの国は？", answer: "日本" },
    { question: "日本三景で宮島・松島・あと1つは？", answer: "天橋立" },
    { question: "スカンジナビアでノルウェー・スウェーデン・あと1つは？", answer: "デンマーク" },
    { question: "三大栄養素で炭水化物・脂質・あと1つは？", answer: "タンパク質" },
    { question: "三権分立で立法・行政・あと1つは？", answer: "司法" },
    { question: "三大宗教建築でモスク・教会・あと1つは？", answer: "寺院" },
    { question: "地球に一番近い惑星は？", answer: "金星" },
    { question: "バレーボールは何人制？", answer: "6人" },
    { question: "“Monday”の10日後は？", answer: "Thursday" },
    { question: "“鬼滅の刃”の主人公は？", answer: "炭治郎" },
    { question: "酸素を運ぶ血液成分は？", answer: "赤血球" },
    { question: "ウォンを使う国は？", answer: "韓国" },
    { question: "ブラジルの首都は？", answer: "ブラジリア" },
    { question: "メキシコの首都は？", answer: "メキシコシティ" },
    { question: "“Tuesday”の10日後は？", answer: "Friday" },
    { question: "“Tuesday”の10日前は？", answer: "Saturday" },
    { question: "“Tuesday”の4日前は？", answer: "Friday" },
    { question: "8チームトーナメントの試合数は？", answer: "7試合" }, 
    { question: "五十音12音目のひらがなは？", answer: "し" } ,
    { question: "3個90円なら10個いくら？", answer: "300円" } ,
    { question: "5個200円なら12個いくら？", answer: "480円" }, 
    { question: "40円で200円は何個買える？", answer: "5個" },
    { question: "50円で300円は何個買える？", answer: "6個" } ,
    { question: "正方形の対角線は何本？", answer: "2本" },
    { question: "ことわざ「ひょうたんから？」", answer: "駒" },
    { question: "木星と土星、地球に近いのは？", answer: "木星" },
    { question: "召し上がるの尊敬語は？", answer: "尊敬語" },
    { question: "米の生産量日本一の県は？", answer: "新潟県" },
    { question: "日食と月食、月が影に入るのは？", answer: "月食" },
    { question: "香川県の県庁所在地は？", answer: "高松市" },
    { question: "4チームトーナメントの試合数は？", answer: "3試合" },
    { question: "鎌倉幕府を開いた人物は？", answer: "源頼朝" },
    { question: "ひなまつりの節句は？", answer: "桃の節句" },
    { question: "日本最大の湖は？", answer: "琵琶湖" },
    { question: "剛田たけしの妹の名前は？", answer: "ジャイ子" },
    { question: "石川県の県庁所在地は？", answer: "金沢市" },
    { question: "0.01を分数にすると？", answer: "1/100" },
    { question: "イモリ・タモリ・ヤモリで両生類は？", answer: "イモリ" },
    { question: "仏の顔も何度まで？", answer: "3度" },
    { question: "太陽が真南にくることは？", answer: "南中" },
    { question: "イチローの背番号は？", answer: "51" },
    { question: "枕草子の作者は？", answer: "清少納言" },
    { question: "参議院の任期は？", answer: "6年" },
    { question: "黒潮と親潮、水温が高いのは？", answer: "黒潮" },
    { question: "1500kgは何トン？", answer: "1.5トン" },
    { question: "岩手県の県庁所在地は？", answer: "盛岡市" },
    { question: "ちりも積もれば何となる？", answer: "山となる" },
    { question: "めしべとおしべ、やくがあるのは？", answer: "おしべ" },
    { question: "サイコロ1の裏は？", answer: "6" },
    { question: "ペナルティエリアとゴールエリア広いのは？", answer: "ペナルティエリア" },
    { question: "りんご生産量日本一の県は？", answer: "青森県" },
    { question: "191を四捨五入すると？", answer: "190" },
    { question: "沖縄県の県庁所在地は？", answer: "那覇市" },
    { question: "安全の反対語は危険、運動の反対語は？", answer: "静止" },
    { question: "「M」で始まる月、Marchともう1つは？", answer: "May" },
    { question: "「J」で始まる月、Julyともう1つは？", answer: "June" },
    { question: "「A」で始まる月、Aprilともう1つは？", answer: "August" }, 
    { question: "2分の3は何％？", answer: "150％" },
    { question: "5分の2は何％？", answer: "40％" },
    { question: "5分の3は何％？", answer: "60％" }, 
    { question: "20％を分数で表すと？", answer: "5分の1" },
    { question: "お笑いコンビ千鳥のノブ。相方は？", answer: "大悟" },
    { question: "サンドウィッチマンの富澤たけし。相方は？", answer: "伊達" },
    { question: "NON STYLEの井上裕介。相方は？", answer: "石田" },
    { question: "アンタッチャブルの柴田英嗣。相方は？", answer: "ザキヤマ" },
    { question: "ダイアンの津田篤宏。相方は？", answer: "ユースケ" },
    { question: "かまいたちの濱家隆一。相方は？", answer: "山内" }, 
    { question: "大化の改新で中大兄皇子と協力した人物は？", answer: "中臣鎌足" },
    { question: "平安京へ遷都した天皇は？", answer: "桓武天皇" },
    { question: "平氏を壇ノ浦で破った武将は？", answer: "源義経" }, 
    { question: "金閣を建てた将軍は？", answer: "足利義満" },
    { question: "種子島に鉄砲が伝来した年は？", answer: "1543年" }, 
    { question: "享保の改革を行った将軍は？", answer: "徳川吉宗" },
    { question: "大塩平八郎の乱が起きた都市は？", answer: "大阪" }, 
    { question: "日清戦争の講和条約は？", answer: "下関条約" },
    { question: "日露戦争の講和条約は？", answer: "ポーツマス条約" }, 
    { question: "BTSの日本での略称は？", answer: "防弾少年団" },
    { question: "YOASOBIの女性ボーカルは？", answer: "ikura（幾田りら）" }, 
    { question: "Mrs. GREEN APPLEのボーカルは？", answer: "大森元貴" },
    { question: "King Gnuのボーカルは？", answer: "井口理" }, 
    { question: "SMAPのリーダーは？", answer: "中居正広" },
    { question: "AKB48の総合プロデューサーは？", answer: "秋元康" }, 
    { question: "BTSの最年長メンバーは？", answer: "ジン" }, 
    { question: "『Automatic』『First Love』この曲のアーティストは？", answer: "宇多田ヒカル" },
    { question: "『Lemon』『LOSER』この曲のアーティストは？", answer: "米津玄師" },
    { question: "『残酷な天使のテーゼ』『魂のルフラン』この曲のアーティストは？", answer: "高橋洋子" }, 
    { question: "『さくらんぼ』『PEACH』この曲のアーティストは？", answer: "大塚愛" }, 
    { question: "『白日』『Slumberland』この曲のアーティストは？", answer: "King Gnu" },
    { question: "『花束』『栞』この曲のアーティストは？", answer: "back number" }, 
    { question: "『HANABI』『Tomorrow never knows』この曲のアーティストは？", answer: "Mr.Children" }, 
    { question: "『小さな恋のうた』『あなたに』この曲のアーティストは？", answer: "MONGOL800" },
    { question: "『さよならエレジー』『虹』この曲のアーティストは？", answer: "菅田将暉" } ,
    { question: "『タイタニック』『アバター』の監督は？", answer: "ジェームズ・キャメロン" }, 
    { question: "『君の名は。』『天気の子』の監督は？", answer: "新海誠" },
    { question: "『千と千尋の神隠し』『となりのトトロ』の監督は？", answer: "宮崎駿" }, 
    { question: "『ハリー・ポッター』の学校名は？", answer: "ホグワーツ" }, 
    { question: "『君の名は。』の主人公の女子の名前は？", answer: "宮水三葉" },
    { question: "『天気の子』の主人公の名前は？", answer: "森嶋帆高" },
    { question: "『鬼滅の刃』の主人公は？", answer: "竈門炭治郎" }, 
    { question: "『地面師たち』『愚か者の身分』に共通する主演俳優は？", answer: "綾野剛" },
    { question: "『半沢直樹』『VIVANT』に共通する主演俳優は？", answer: "堺雅人" },
    { question: "『コード・ブルー』『グランメゾン東京』に共通する主演俳優は？", answer: "木村拓哉" }, 
    { question: "『ドクターX』『黒革の手帖』に共通する主演女優は？", answer: "米倉涼子" }, 
    { question: "『3年A組』『ニッポンノワール』に共通する主演俳優は？", answer: "菅田将暉" },
    { question: "『あまちゃん』『海のはじまり』に共通する主演女優は？", answer: "有村架純" }, 
    { question: "「蚊」を英語で言うと？", answer: "mosquito" },
    { question: "「バス停」を英語で言うと？", answer: "bus stop" }, 
    { question: "「努力」を英語で言うと？", answer: "effort" },
    { question: "「改善」を英語で言うと？", answer: "improvement" },
    { question: "「成長」を英語で言うと？", answer: "growth" },
    { question: "「交渉」を英語で言うと？", answer: "negotiation" },
    { question: "「提案」を英語で言うと？", answer: "proposal" },
    { question: "「契約」を英語で言うと？", answer: "contract" },
    { question: "「競争」を英語で言うと？", answer: "competition" },
    { question: "「定規」を英語で言うと？", answer: "ruler" }, 
    { question: "夏目漱石・芥川龍之介・村上春樹で現代作家は？", answer: "村上春樹" }, 
    { question: "CPU・GPU・RAMで記憶装置は？", answer: "RAM" }, 
    { question: "卑弥呼・推古天皇・持統天皇で最も古い時代は？", answer: "卑弥呼" },
    { question: "鎌倉・室町・江戸で最も長く続いた幕府は？", answer: "江戸" },
    { question: "明治・大正・昭和で最も短い元号は？", answer: "大正" },
    { question: "聖徳太子・菅原道真・藤原道長で摂関政治に関係するのは？", answer: "藤原道長" } ,
    { question: "ヘリウム・水素・ネオンで最も原子番号が小さいのは？", answer: "水素" },
    { question: "酸素・窒素・二酸化炭素で大気中に最も多いのは？", answer: "窒素" }, 
    { question: "光・音・電波で真空中を伝わるのは？", answer: "光" },
    { question: "電流・電圧・抵抗で単位がボルトなのは？", answer: "電圧" }, 
    { question: "2月11日は何の日？", answer: "建国記念の日" }, 
    { question: "4月29日は何の日？", answer: "昭和の日" },
    { question: "5月3日は何の日？", answer: "憲法記念日" },
    { question: "11月3日は何の日？", answer: "文化の日" },
    { question: "11月23日は何の日？", answer: "勤労感謝の日" }, 
    { question: "植物細胞で光合成を行う緑の粒は？", answer: "葉緑体" },
    { question: "地震の初期微動を起こす波は？", answer: "P波" },
    { question: "水蒸気が水滴になり始める温度は？", answer: "露点" },
    { question: "バッタやカニなど節のある動物の仲間は？", answer: "節足動物" },
    { question: "水に溶けて電流が流れる物質は？", answer: "電解質" },
    { question: "光が水やガラスで曲がる現象は？", answer: "屈折" },
    { question: "酸とアルカリが打ち消し合う反応は？", answer: "中和" } ,
    { question: "セブンイレブンを運営する日本企業は？", answer: "セブン＆アイ・ホールディングス" },
    { question: "ローソンを運営する企業は？", answer: "三菱商事系ローソン" },
    { question: "ファミリーマートの親会社は？", answer: "伊藤忠商事" }, 
    { question: "ナイキの本社がある国は？", answer: "アメリカ" },
    { question: "アディダスの本社がある国は？", answer: "ドイツ" },
    { question: "プーマの本社がある国は？", answer: "ドイツ" },
    { question: "シャネルの創業国は？", answer: "フランス" }, 
    { question: "ユニクロを展開する会社は？", answer: "ファーストリテイリング" },
    { question: "無印良品を展開する会社は？", answer: "良品計画" }, 
    { question: "TeslaのCEOは誰？", answer: "イーロン・マスク" },
    { question: "NVIDIAの主力製品は何チップ？", answer: "GPU" },
    { question: "TSMCは何を製造する企業？", answer: "半導体" },
    { question: "Samsungの本社がある国は？", answer: "韓国" },
    { question: "Huaweiの本社がある国は？", answer: "中国" }, 
    { question: "イタリアの代表的な米料理は？", answer: "リゾット" },
    { question: "イタリアの生ハムで有名なのは？", answer: "プロシュート" }, 
    { question: "ロシアのスープ料理は？", answer: "ボルシチ" },
    { question: "トルコの回転焼肉は？", answer: "ドネルケバブ" }, 
    { question: "ハンバーグのルーツに近い料理の発祥国は？", answer: "ドイツ" },
    { question: "シュニッツェルの発祥国は？", answer: "オーストリア" },
    { question: "チーズフォンデュの発祥国は？", answer: "スイス" }, 
    { question: "ナポリタンの発祥国は？", answer: "日本" },
    { question: "天ぷらの起源に影響を与えた国は？", answer: "ポルトガル" }, 
    { question: "味噌カツの発祥県は？", answer: "愛知県" },
    { question: "ひつまぶしの発祥県は？", answer: "愛知県" }, 
    { question: "『となりのトトロ』でサツキの妹は？", answer: "メイ" },
    { question: "『となりのトトロ』でトトロが住んでいる場所は？", answer: "クスノキの森" },
    { question: "『千と千尋の神隠し』で千尋が働く場所は？", answer: "油屋" }, 
    { question: "『千と千尋の神隠し』で千尋の両親が変えられた動物は？", answer: "豚" },
    { question: "『もののけ姫』でアシタカの村の特徴は？", answer: "エミシの村" }, 
    { question: "『魔女の宅急便』でキキの相棒の黒猫は？", answer: "ジジ" }, 
    { question: "ミッキーの犬の名前は？", answer: "プルート" },
    { question: "ドナルドダックの恋人は？", answer: "デイジーダック" }, 
    { question: "『アラジン』でランプの精は？", answer: "ジーニー" },
    { question: "『アラジン』でアラジンの恋人は？", answer: "ジャスミン" }, 
    { question: "『トイ・ストーリー』で主人公のおもちゃは？", answer: "ウッディ" },
    { question: "『トイ・ストーリー』で宇宙ヒーローは？", answer: "バズ・ライトイヤー" }, 
    { question: "『ファインディング・ニモ』で父親は？", answer: "マーリン" },
    { question: "『ファインディング・ニモ』で忘れっぽい魚は？", answer: "ドリー" }, 
    { question: "『進撃の巨人』で壁の中の人類が住む都市は？", answer: "パラディ島" },
    { question: "『進撃の巨人』で主人公の名前は？", answer: "エレン・イェーガー" }, 
    { question: "『ナルト』でナルトの親友は？", answer: "サスケ" }, 
    { question: "『ドラゴンボール』で悟空の必殺技は？", answer: "かめはめ波" },
    { question: "『ドラゴンボール』で宇宙人の敵は？", answer: "フリーザ" }, 
    { question: "『名探偵コナン』で主人公の本名は？", answer: "工藤新一" }, 
    { question: "USBのUは何を表す？", answer: "ユニバーサル" },
    { question: "USBのSは何を表す？", answer: "シリアル" },
    { question: "USBのBは何を表す？", answer: "バス" },
    { question: "HTMLのHは何を表す？", answer: "ハイパー" },
    { question: "HTMLのTは何を表す？", answer: "テキスト" },
    { question: "HTMLのMは何を表す？", answer: "マークアップ" },
    { question: "HTMLのLは何を表す？", answer: "言語" }, 
    { question: "IOCのOは何を表す？", answer: "オリンピック" }, 
    { question: "WHOのHは何を表す？", answer: "保健" }, 
    { question: "イースター島のモアイ像がある国は？", answer: "チリ" }, 
    { question: "ギザのピラミッドの中で最大は？", answer: "クフ王のピラミッド" }, 
    { question: "サグラダ・ファミリアの建築家は？", answer: "ガウディ" },
    { question: "コロッセオがあるイタリアの都市は？", answer: "ローマ" }, 
    { question: "パルテノン神殿がある丘は？", answer: "アクロポリスの丘" }, 
    { question: "イグアスの滝はアルゼンチンとどこの国境？", answer: "ブラジル" }, 
    { question: "ハロン湾がある国は？", answer: "ベトナム" }, 
    { question: "カッパドキアがある国は？", answer: "トルコ" }, 

  ],

  /* ============================================================
     中級 (medium) - 2択・日常の一般常識
     ============================================================ */
  medium: [
    { question: "かつて「ペルシャ」と呼ばれていた国はどこ？", answer: "イラン" },
    { question: "2020年に開業した山手線の新駅。高輪何？", answer: "高輪ゲートウェイ" },
    { question: "お笑いコンビ「ぺこぱ」、松陰寺太勇の相方は誰？", answer: "シュウペイ" },
    { question: "焼肉のホルモン。実在するのはハチノス・クモノスどっち？", answer: "ハチノス" },
    { question: "腎臓と膵臓、人間の体に「左右に2つ」あるのは？", answer: "腎臓" },
    { question: "プロ野球の「沢村賞」。対象になるのは投手・打者どっち？", answer: "投手" },
    { question: "ミシンで服を縫うときに使うのは、イヌ・サル・キジどれ？", answer: "キジ" },
    { question: "元素記号「Li」で表される、バッテリー用の金属は？", answer: "リチウム" },
    { question: "相撲で「白星、黒星、金星」を1つずつ取ったら、何勝？", answer: "2勝" },
    { question: "立方体の1辺を2倍にすると、体積は何倍になる？", answer: "8倍" },
    { question: "英語の「ユーモア」。頭文字のアルファベットは？", answer: "H" },
    { question: "ことわざ。「火中の何（食べ物）を拾う」？", answer: "栗" },
    { question: "ダチョウ、コウモリ、ペンギン。鳥類ではないのは？", answer: "コウモリ" },
    { question: "「減塩（げんえん）」の「塩」という漢字、訓読みで何？", answer: "しお" },
    { question: "探査機「はやぶさ2」が、砂を持ち帰った小惑星は？", answer: "リュウグウ" },
    { question: "リビアとシリア。アフリカ大陸にある国はどっち？", answer: "リビア" },
    { question: "バスの停留所を英語で言うと、「バス・何」？", answer: "ストップ" },
    { question: "世界遺産・白川郷の「合掌造り」があるのは何県？", answer: "岐阜県" },
    { question: "マナミ、環奈. 共通する名字は？", answer: "橋本" },
    { question: "ダイヤモンドなど、宝石の重さを表す単位は？", answer: "カラット" },
    { question: "観光地の「ワイキキビーチ」は、アメリカの何州にある？", answer: "ハワイ州" },
    { question: "環境活動家グレタ・トゥンベリさんの出身国はどこ？", answer: "スウェーデン" },
    { question: "早稲田大学を創立した、明治時代の総理大臣は誰？", answer: "大隈重信" },
    { question: "通信規格の「5G」や「6G」。この「G」は何の略？", answer: "ジェネレーション" },
    { question: "海王星と天王星、太陽により近い惑星はどっち？", answer: "天王星" },
    { question: "高校野球の聖地「甲子園球場」があるのは兵庫県の何市？", answer: "西宮市" },
    { question: "音楽ユニット「YOASOBI」のメインボーカルは誰？", answer: "ikura" },
    { question: "東北新幹線から山形新幹線が分岐する、福島県の駅は？", answer: "福島駅" },
    { question: "日本の「都道府県知事」は、何歳から立候補できる？", answer: "30歳" },
    { question: "今何問目？", answer: "(画面を確認して)" },
    { question: "今何問目？", answer: "(画面を確認して)" },
    { question: "今何問目？", answer: "(画面を確認して)" },
    { question: "今何問目？", answer: "(画面を確認して)" },
    { question: "今何問目？", answer: "(画面を確認して)" },
    { question: "あと何問で終わり？", answer: "(画面を確認して)" },
    { question: "あと何問で終わり？", answer: "(画面を確認して)" },
    { question: "あと何問で終わり？", answer: "(画面を確認して)" },
    { question: "あと何問で終わり？", answer: "(画面を確認して)" },
    { question: "あと何問で終わり？", answer: "(画面を確認して)" },
    { question: "バトゥ洞窟の名物は巨大な誰の像？", answer: "ムルガン神" },
    { question: "三大発明で火薬・羅針盤・あと1つは？", answer: "印刷術" },
    { question: "ASEAN本部がある国は？", answer: "インドネシア" },
    { question: "世界貿易機関をアルファベット3文字で？", answer: "WTO" },
    { question: "Jalanの意味は？", answer: "道" },
    { question: "Tamanの意味は？", answer: "公園" },
    { question: "ナシレマを包む葉は何の葉？", answer: "バナナの葉" },
    { question: "リンギット紙幣で最高額は？", answer: "100リンギット" },
    { question: "ペトロナスツインタワーは何階建て？", answer: "88階" },
    { question: "マレーシア独立日は何月何日？", answer: "8月31日" },
    { question: "ローマ帝国初代皇帝は？", answer: "アウグストゥス" },
    { question: "万里の長城を築いた国は？", answer: "秦" },
    { question: "世界一周した人物は？", answer: "マゼラン" },
    { question: "EU本部はどこ？", answer: "ブリュッセル" },
    { question: "ノーベル賞発祥の国は？", answer: "スウェーデン" },
    { question: "中国の国である秦と漢、先はどっち？", answer: "秦" },
    { question: "十字軍が目指した都市は？", answer: "エルサレム" },
    { question: "インド航路発見は誰？", answer: "バスコ・ダ・ガマ" },
    { question: "太陽王と呼ばれたフランス人は？", answer: "ルイ14世" },
    { question: "オスマン帝国の首都は？", answer: "イスタンブール" },
    { question: "百年戦争で活躍した少女は？", answer: "ジャンヌ・ダルク" },
    { question: "バルト三国でエストニア・ラトビア・あと1つは？", answer: "リトアニア" },
    { question: "世界三大宗教都市でメッカ・ローマ・あと1つは？", answer: "エルサレム" },
    { question: "三大映画祭でカンヌ・ベネチア・あと1つは？", answer: "ベルリン" },
    { question: "AppleとMicrosoft、創業が古いのはどっち？", answer: "Microsoft" },
    { question: "WindowsとMac、シェアが大きいのはどっち？", answer: "Windows" },
    { question: "H&MとZARA、スペイン発祥はどっち？", answer: "ZARA" },
    { question: "JALとANA、国際線が多いのはどっち？", answer: "ANA" },
    { question: "二人三脚出てくる数字を足すと？", answer: "5" },
    { question: "三人四脚に出てくる数字を足すと？", answer: "7" }, 
    { question: "七五三の数字を足すと？", answer: "15" }, 
    { question: "三寒四温の数字を足すと？", answer: "7" }, 
    { question: "ミッキーとドナルド、米大統領は？", answer: "トランプ" },
    { question: "江戸時代の大阪は天下の？", answer: "台所" },
    { question: "漢字のだそくに出る生き物は？", answer: "蛇" },
    { question: "キャビアとトリュフ、魚の卵は？", answer: "キャビア" },
    { question: "落札と入札、手に入れるのは？", answer: "落札" },
    { question: "円の直径2倍で面積は何倍？", answer: "4倍" },
    { question: "4チームトーナメントの試合数は？", answer: "3試合" },
    { question: "金・銀・銅、将棋に無いのは？", answer: "銅" },
    { question: "東京は都知事、大阪は？", answer: "府知事" },
    { question: "ハロウィーンは何月？", answer: "10月" },
    { question: "五十音9音目のひらがなは？", answer: "け" },
    { question: "祖父と祖母、お母の父は？", answer: "祖父" },
    { question: "ミシュラン最高星はいくつ？", answer: "3" },
    { question: "4個120円、10個いくら？", answer: "300円" },
    { question: "有機物と無機物、ミネラルは？", answer: "無機物" },
    { question: "挨拶で交換するものは？", answer: "名刺" },
    { question: "伴奏なしで歌うカタカナ4文字は？", answer: "アカペラ" },
    { question: "5・6・7で素数でないのは？", answer: "6" },
    { question: "加賀野菜は何県？", answer: "石川県" },
    { question: "ダブルはハーフの何倍？", answer: "2倍" },
    { question: "ナタデココ逆から読むと？", answer: "ココデタナ" },
    { question: "コンビとトリオ合わせて何人？", answer: "5人" },
    { question: "浜名湖は何の養殖で有名？", answer: "うなぎ" },
    { question: "葉を落とす樹木は？", answer: "落葉樹" },
    { question: "ハリー・ポッターの飼い鳥は？", answer: "ヘドウィグ" },
    { question: "お世辞サービスは何サービス？", answer: "リップサービス" },
    { question: "せっけっきゅうに出る色は？", answer: "赤" },
    { question: "30円で100円は何個買える？", answer: "3個" },
    { question: "さるかに合戦の悪者は？", answer: "さる" },
    { question: "キャサリンとオードリーの名字は？", answer: "ヘプバーン" },
    { question: "プノンペンの国は？", answer: "カンボジア" },
    { question: "能ある鷹が隠すのは？", answer: "爪" },
    { question: "ミノとノミ、焼肉は？", answer: "ミノ" },
    { question: "襟足があるのは上半身？", answer: "上半身" },
    { question: "きしょうてんけつの糸偏は？", answer: "結" },
    { question: "1万円で880円お釣りは元値いくら？", answer: "9120円" },
    { question: "おとといとおととし近いのは？", answer: "おととい" },
    { question: "首相夫人の呼び名は？", answer: "ファーストレディ" },
    { question: "かぐや姫が帰る星は？", answer: "月" },
    { question: "火のない所に立たないのは？", answer: "煙" },
    { question: "アンとトモヤの名字は？", answer: "なし" },
    { question: "海のミルクと呼ばれるのは？", answer: "牡蠣" },
    { question: "リコーダーは縦笛？横笛？", answer: "縦笛" }, 
      { question: "1cmは「？mm」", answer: "10mm" },
      { question: "金属の「アルミ」略さず言うと？", answer: "アルミニウム" },
      { question: "「さんじ・よじ・ごじ」字を間違えるのは？", answer: "よじ" },
      { question: "「500円の3割引」いくら？", answer: "350円" },
      { question: "知らないフリをする「？を切る」", answer: "白を切る" },
      { question: "映画のサントラ「サン」は何の略？", answer: "サウンド" },
      { question: "ピアノの詩人は「ショパン」魔術師は？", answer: "リスト" },
      { question: "柔道と茶道「武道」はどっち？", answer: "柔道" },
      { question: "1日の4分の1は何時間？", answer: "6時間" },
      { question: "「シルクロード」日本語で「？の道」", answer: "絹の道" },
      { question: "試合終了で「ノーサイド」このスポーツは？", answer: "ラグビー" },
      { question: "あたたかい「温？」送り仮名は？", answer: "かい" },
      { question: "「風のように走るメロス」のように、名詞で終わる表現方法は？", answer: "体言止め" },
      { question: "実践じっせんの対義語は？", answer: "空論" },
      { question: "4と6の最小公倍数は？", answer: "12" },
      { question: "六角形の内角の和は？", answer: "720度" },
      { question: "太陽から1番遠い惑星は？", answer: "海王星" },
      { question: "「NH3」この化合物は？", answer: "アンモニア" },
      { question: "「アンブレラ（傘）」アルファベットの頭文字は？", answer: "U" },
      { question: "まつげは「eyelash」まゆげは「eye？」", answer: "eyebrow" },
      { question: "背骨が無い動物＝無○○動物", answer: "脊椎" },
      { question: "1L=？dL", answer: "10dL" },
      { question: "10万円の2割引から、さらに1割引。さていくら？", answer: "72000円" },
      { question: "3分の1を英語で言うと？", answer: "one third" },
      { question: "文学作品「注文の多い料理店」の作者は？", answer: "宮沢賢治" },
      { question: "特定保健用食品をカタカナ3文字で？", answer: "トクホ" },
      { question: "森鴎外の「舞姫」で主人公が留学した国は？", answer: "ドイツ" },
      { question: "元素記号「Fe」この金属は？", answer: "鉄" },
      { question: "「松」は裸子植物「桜」は？", answer: "被子植物" },
      { question: "江戸時代の庶民の学校は○○屋", answer: "寺子屋" },
      { question: "1ドル100円が90円に。円高？円安？", answer: "円高" },
      { question: "イギリス〜フランス間を結ぶ高速列車は？", answer: "ユーロスター" },
      { question: "13＋54＋27＝？", answer: "94" },
      { question: "160×11＝？", answer: "1760" },
      { question: "明けの明星は金星、では宵の明星は？", answer: "金星" },
      { question: "今日は水曜日として、昨日の明後日は何曜日？", answer: "月曜日" },
      { question: "電卓の数字すべて掛けるといくつ？", answer: "0" },
      { question: "1分間で100万円を時給に直すと？", answer: "6000万円" },
      { question: "あなたのお父さんのお母さんは妹の何？", answer: "祖母" },
      { question: "オランダ語の「蜂の巣」が語源のお菓子は？", answer: "ワッフル" },
      { question: "「青春18きっぷ」19歳以上は買える？買えない？", answer: "買える" },
      { question: "アナゴ・イナゴ・タナゴ　昆虫はどれ？", answer: "イナゴ" },
      { question: "「敵は本能寺にあり」敵は誰？", answer: "明智光秀" },
      { question: "プロ野球で東京都の球団は巨人と何？", answer: "ヤクルト" },
      { question: "テニスの「ジョコビッチ」どこの国の選手？", answer: "セルビア" },
      { question: "「おい・めい・いとこ」5月は？", answer: "May" },
      { question: "Spotify、IKEA、H＆Mどこの国？", answer: "スウェーデン" },
      { question: "「ちゃんちゃん焼き」「石狩鍋」メインの魚は？", answer: "鮭" },
      { question: "高知の「桂浜」誰の銅像がある？", answer: "坂本龍馬" },
      { question: "ビリヤード台で空いている穴の名前は？", answer: "ポケット" },
      { question: "「氷点下」気温は摂氏○度以下？", answer: "0度" },
      { question: "自衛隊を管轄するのは何省？", answer: "防衛省" },
      { question: "キムチの「カクテキ」何の野菜を使う？", answer: "大根" },
      { question: "600円の2割増しは？", answer: "720円" },
      { question: "ロンドン・パリ・ニューヨーク、首都で無いのは？", answer: "ニューヨーク" },
      { question: "名古屋名物「ひつまぶし」使う魚は？", answer: "うなぎ" },
      { question: "シベリアとリベリア、国名はどっち？", answer: "リベリア" },
      { question: "アルファベット順「T」の1つ前は？", answer: "S" },
      { question: "オスとメス、調味料はどっち？", answer: "メス" },
      { question: "「8分の1」小数でいくつ？", answer: "0.125" },
      { question: "ツンデレとツンドラ、ロシア語は？", answer: "ツンドラ" },
      { question: "桜の名所「弘前城」ここは何県？", answer: "青森県" },
      { question: "トランプ「七並べ」最初に出せるのは6と何？", answer: "8" },
      { question: "ミュージカル「ミス・サイゴン」舞台の国は？", answer: "ベトナム" },
      { question: "季節風と偏西風、モンスーンは？", answer: "季節風" },
      { question: "声を出さずに読む＝○読？", answer: "黙読" },
      { question: "日本三大随筆で枕草子・方丈記・あと1つは？", answer: "徒然草" },
      { question: "3tは何kg？", answer: "3000kg" },
      { question: "合計1400円でお釣り100円。いくら払った？", answer: "1500円" },
      { question: "6の約数、2・3・6。あと1つは？", answer: "1" },
      { question: "光と音、空気を伝わるのが早いのは？", answer: "光" },
      { question: "晴れた夜に地面が冷え込む現象＝何冷却？", answer: "放射冷却" },
      { question: "東海道五十三次のスタート地点は？", answer: "日本橋" },
      { question: "1933年の大恐慌でルーズベルト大統領が行った政策は？", answer: "ニューディール政策" },
      { question: "三権分立を説いた『法の精神』の著者は？", answer: "モンテスキュー" },
      { question: "食べるの尊敬語は？", answer: "召し上がる" },
      { question: "森鴎外の職業は文学者（作家）と何？", answer: "医師" },
      { question: "「頭・顔」共通する部首は？", answer: "頁（おおがい）" },
      { question: "ヨウ素液で青紫に。この成分は？", answer: "デンプン" },
      { question: "デオキシリボ核酸をアルファベット3文字で？", answer: "DNA" },
      { question: "茄子（ナス）を英語でいうと？", answer: "eggplant" },
      { question: "絵具の青と黄色を混ぜると何色？", answer: "緑" },
      { question: "10月は神無月。では11月は？", answer: "霜月" },
      { question: "人は肺呼吸。魚のフナは何呼吸？", answer: "えら呼吸" },
      { question: "アンモニアは水素と何でできている？", answer: "窒素" },
      { question: "120cmと132cm、差は何cm？", answer: "12cm" },
      { question: "25mは何cm？", answer: "2500cm" },
      { question: "2時間30分は何分？", answer: "150分" },
      { question: "180秒は何分？", answer: "3分" }, 
      { question: "力を受けないとその場にとどまる＝○○の法則", answer: "慣性" },
      { question: "1932年 犬養毅が暗殺された事件＝○○○事件", answer: "五・一五事件" },
      { question: "エレベーターの「R」何の略？", answer: "Roof" },
      { question: "牛乳を生産する農業＝○農", answer: "酪農" },
      { question: "具体的の対義語は？", answer: "抽象的" },
      { question: "勝利の対義語は？", answer: "敗北" },
      { question: "前進の対義語は？", answer: "後退" },
      { question: "需要の対義語は？", answer: "供給" },
      { question: "サイコロで3が出る確率は？", answer: "6分の1" },
      { question: "マチュピチュ遺跡を築いた帝国は？", answer: "インカ帝国" },
      { question: "サグラダ・ファミリアがある都市は？", answer: "バルセロナ" },
      { question: "モアイ像がある島は？", answer: "イースター島" },
      { question: "ストーンヘンジがある国は？", answer: "イギリス" }, 
      { question: "ナスカの地上絵がある国は？", answer: "ペルー" },
      { question: "アルハンブラ宮殿がある国は？", answer: "スペイン" }, 
      { question: "バレーボールでレシーブ専門の選手は？", answer: "リベロ" },
      { question: "ドルフィンキックを使う泳法は？", answer: "バタフライ" },
      { question: "ラグビーのトライは何点入る？", answer: "5点" },
      { question: "バスケットボールで片足を軸に動くことを何という？", answer: "ピボット" },
      { question: "3×3＋3＝", answer: "12" },
      { question: "75％を分数で表すと？", answer: "4分の3" },
      { question: "2、5、6の最小公倍数は？", answer: "30" },
      { question: "ドライアイスは何が固まったもの？", answer: "二酸化炭素" },
      { question: "good の比較級は？", answer: "better" },
      { question: "年利3％で10万円貯金。1年後の利子は？", answer: "3000円" },
      { question: "乾電池の単2と単3、太いのは？", answer: "単2" },
      { question: "英語でモスキート、この虫は？", answer: "蚊" },
      { question: "歌手のジャクソン、NBAのジョーダン。共通する名前は？", answer: "マイケル" }, 
      { question: "歌手のマーズ、サッカーのフェルナンデス。共通する名前は？", answer: "ブルーノ" }, 
      { question: "俳優のディカプリオ、画家のダ・ヴィンチ。共通する名前は？", answer: "レオナルド" }, 
      { question: "サッカーはJリーグ、バスケは何リーグ？", answer: "Bリーグ" },
      { question: "仕事を怠けること＝○を売る？", answer: "油" },
      { question: "秘密をもらす＝口が○い？", answer: "軽い" },
      { question: "驚いて言葉を失う＝○を失う？", answer: "声" },
      { question: "努力が無駄になる＝水の○？", answer: "泡" },
      { question: "東海道新幹線。東京、品川の次は", answer: "新横浜" },
      { question: "東北新幹線。東京、上野の次は", answer: "大宮"},
      { question: "原宿、恵比寿、五反田(ごたんだ)。ビールの名前は", answer: "えびす" },
      { question: "東京国際空港は羽田と成田どっち？", answer: "羽田" },
      { question: "関西空港と伊丹(いたみ)空港。大阪市に近いのは", answer: "伊丹" },
      { question: "東京が午前九時。韓国は何時？", answer: "午前九時" },
      { question: "チュートリアル、ロバート、ナイツ。お笑いトリオは？", answer: "ロバート" },
      { question: "ダイアン、ジャングルポケット、銀シャリ。お笑いトリオは？", answer: "ジャングルポケット" },
      { question: "かまいたち、四千頭身、ミキ。お笑いトリオは？", answer: "四千頭身" },
      { question: "インパルス、東京03、中川家。お笑いトリオは？", answer: "東京03" }, 

  ],

  /* ============================================================
     上級 (hard) - ハイレベル・2択・時事
     ============================================================ */
  hard: [
    { question: "DNAの特徴的なねじれ構造を「何構造」と言う？", answer: "二重らせん" },
    { question: "ハイゼンベルクが提唱した量子力学の原理は、「何原理」？", answer: "不確定性" },
    { question: "直角三角形の計算に使う三平方の定理の別名は、「何の定理」？", answer: "ピタゴラス" },
    { question: "シェイクスピアの四大悲劇。ハムレット、マクベス、リア王と？", answer: "オセロー" },
    { question: "前の2つの数を足していく「1, 1, 2, 3, 5...」の数列は？", answer: "フィボナッチ" },
    { question: "元素周期表において、一番最初の「原子番号1番」の元素は？", answer: "水素" },
    { question: "植物の光合成で、二酸化炭素と反応させる根から吸う液体は？", answer: "水" },
    { question: "元素周期表の原子番号79番。金を表す元素記号は何？", answer: "Au" },
    { question: "ケガをした時など、人体の血液凝固に関わるビタミンは何？", answer: "ビタミンK" },
    { question: "1867年に『資本論』を著したドイツの思想家は誰？", answer: "マルクス" },
    { question: "ディスプレイに使われる「光の三原色」を英字3文字で？", answer: "RGB" },
    { question: "電流を一定方向にしか流さない、pn接合で作られた電子部品は？", answer: "ダイオード" },
    { question: "お役所「農水省」の「水」は、何の略？", answer: "水産" },
    { question: "縄文土器と弥生土器。東京都の地名に由来するのはどっち？", answer: "弥生土器" },
    { question: "タレントの「みちょぱ」と「エライザ」。共通する名字は？", answer: "池田" },
    { question: "野球の打率。5打数2安打だった場合、打率は「何割」？", answer: "4割" },
    { question: "ナシゴレンやミーゴレンの発祥国である、東南アジアの国はどこ？", answer: "インドネシア" },
    { question: "聖徳太子が「冠位十二階」を制定した当時の女性の天皇は誰？", answer: "推古天皇" },
    { question: "「いざという時の切り札」を意味する言葉。「伝家の何」？", answer: "宝刀" },
    { question: "東南アジアの麺料理「ビーフン」の原料となる穀物は何？", answer: "米" },
    { question: "カマキリとホタル。成長の過程で「さなぎ」になるのはどっち？", answer: "ホタル" },
    { question: "「明後日（あさって）」の次の日を漢字で書くと何文字？", answer: "4文字" },
    { question: "「東京証券取引所」の一般的な漢字2文字の略称は何？", answer: "東証" },
    { question: "パソコンの機械をハードウェア、では内部のプログラムは？", answer: "ソフトウェア" },
    { question: "天守閣が国宝に指定されている、長野県松本市にあるお城は？", answer: "松本城" },
    { question: "現在のロシア連邦で使われている公式の通貨単位は何？", answer: "ルーブル" },
    { question: "クラシックの名曲『四季』を作曲した、ベネチア出身の音楽家は？", answer: "ヴィヴァルディ" },
    { question: "恐竜たちが最も大繁栄した時代は、古生代・中生代どっち？", answer: "中生代" },
    { question: "メレンゲを作るときに泡立てるのは、卵の白身・黄身どっち？", answer: "白身" },
    { question: "日本の野菜「カボチャ」の漢字の別名は、北京・南京どっち？", answer: "南京" },
    { question: "小説のタイトル。プリンスエドワード島を舞台にした、何毛のアン？", answer: "赤毛" },
    { question: "宝石の「パール」を、純粋な日本語で言うと何？", answer: "真珠" },
    { question: "サーブ、レシーブ、トス。佐賀県にある都市の名前と同じなのは何？", answer: "トス" },
    { question: "乾いた風により周辺の気温が著しく高くなる現象を何現象と言う？", answer: "フェーン" },
    { question: "飛行機の操縦席「コックピット」。コック（cock）は何の動物のオス？", answer: "ニワトリ" },
    { question: "行動展示で有名な「旭山動物園」があるのは北海道の何市？", answer: "旭川市" },
    { question: "世界一乗降客数が多い駅としてギネスに載る東京の駅は？", answer: "新宿駅" },
    { question: "BLACKPINKのメンバーで、唯一韓国出身ではないのは誰？", answer: "LISA" },
    { question: "大ヒット曲『Subtitle』を歌う4人組バンドは誰？", answer: "Official髭男dism" },
    { question: "日本の淡路島（あわじしま）は、何県に属している？", answer: "兵庫県" },
    { question: "英語試験「TOEIC」の満点スコアは何点？", answer: "990点" },
    { question: "ベトナムの首都はどこ？", answer: "ハノイ" },
    { question: "国際連合（国連）の本部ビルがあるアメリカの都市は？", answer: "ニューヨーク" },
    { question: "マレーシアの南にあるシンガポールは、北半球・南半球どっち？", answer: "北半球" },
    { question: "ジョブズとマスク。アメリカ出身でないのは？", answer: "マスク" },
    { question: "ヒット曲『Die With A Smile』。ブルーノ・マーズと誰の曲？", answer: "レディー・ガガ" },
    { question: "日本の市区町村の中で、最も人口が多い都市はどこ？", answer: "横浜市" },
    { question: "伊豆諸島は、何という都道府県に属する？", answer: "東京都" },
    { question: "今年（2026年）は、日本の元号で言うと令和何年？", answer: "令和8年" },
    { question: "TOEICとTOEFL。スピーキングが必須なのはどっち？", answer: "TOEFL" },
    { question: "歌手の桑田、サッカーの本田。共通する下の名前は？", answer: "ケイスケ" },
    { question: "厳島神社の大鳥居がある、広島県の有名な島はどこ？", answer: "宮島" },
    { question: "リゾート地として有名な「バリ島」は、北半球・南半球どっち？", answer: "南半球" },
    { question: "日本時間は、イギリスのロンドンより何時間進んでいる？", answer: "9時間" }
  ]

};